import {
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Command,
  Copy,
  CreditCard,
  FileCheck2,
  FilePenLine,
  FileText,
  Home,
  LayoutGrid,
  LogOut,
  Menu,
  Moon,
  Palette,
  PencilLine,
  Plus,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Sun,
  Target,
  Trash2,
  User,
  X,
} from "lucide-react";

const icons = {
  admin: ShieldCheck,
  ai: Sparkles,
  ats: Target,
  chart: BarChart3,
  billing: CreditCard,
  check: Check,
  activity: Clock3,
  chevronDown: ChevronDown,
  command: Command,
  copy: Copy,
  coverLetter: FilePenLine,
  dashboard: Home,
  document: FileText,
  documentReady: FileCheck2,
  edit: PencilLine,
  resumeEdit: SquarePen,
  help: CircleHelp,
  jobs: BriefcaseBusiness,
  logout: LogOut,
  menu: Menu,
  moon: Moon,
  notifications: Bell,
  plus: Plus,
  profile: User,
  search: Search,
  settings: Settings,
  sun: Sun,
  templates: Palette,
  trash: Trash2,
  workspace: LayoutGrid,
  close: X,
  collapse: ChevronLeft,
  expand: ChevronRight,
};

export const AppIcon = ({ name, size = 20, strokeWidth = 1.8, ...props }) => {
  const Icon = icons[name];
  if (!Icon) return null;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
};
