UPDATE templates
SET configuration = jsonb_build_object(
    'key', 'professional',
    'version', 1,
    'layout', 'single',
    'defaultTheme', 'professional',
    'sectionOrder', jsonb_build_array('SUMMARY','EXPERIENCE','SKILLS','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),
    'supportedSections', jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),
    'theme', jsonb_build_object('primary','#17212b','accent','#31546d','text','#17212b','muted','#52606d','border','#9aa5b1','headingFont','TIMES','bodyFont','TIMES')
)
WHERE name = 'classic';

INSERT INTO templates (name, description, is_system, is_active, configuration)
VALUES
('modern', 'Clean sans-serif layout with a crisp blue accent.', TRUE, TRUE, jsonb_build_object('key','modern','version',1,'layout','single','defaultTheme','modern-blue','sectionOrder',jsonb_build_array('SUMMARY','SKILL','EXPERIENCE','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','SKILL','EXPERIENCE','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#102a43','accent','#2563eb','text','#102a43','muted','#52667a','border','#bfdbfe','headingFont','HELVETICA','bodyFont','HELVETICA'))),
('professional', 'Conservative layout for finance, legal, and traditional roles.', TRUE, TRUE, jsonb_build_object('key','professional','version',1,'layout','single','defaultTheme','professional','sectionOrder',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','PROJECT','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','PROJECT','LANGUAGES'),'theme',jsonb_build_object('primary','#17212b','accent','#31546d','text','#17212b','muted','#52606d','border','#9aa5b1','headingFont','TIMES','bodyFont','TIMES'))),
('creative', 'Bold two-column presentation for creative and marketing work.', TRUE, TRUE, jsonb_build_object('key','creative','version',1,'layout','sidebar','defaultTheme','creative-coral','sectionOrder',jsonb_build_array('SUMMARY','PROJECT','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'sidebarSections',jsonb_build_array('SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','PROJECT','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#3b174f','accent','#e35d6a','text','#281331','muted','#715b78','border','#f3b8bf','headingFont','HELVETICA','bodyFont','HELVETICA'))),
('minimal', 'Maximum whitespace and restrained typography for ATS-focused applications.', TRUE, TRUE, jsonb_build_object('key','minimal','version',1,'layout','single','defaultTheme','minimal','sectionOrder',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#111827','accent','#111827','text','#111827','muted','#6b7280','border','#d1d5db','headingFont','HELVETICA','bodyFont','HELVETICA'))),
('executive', 'Formal, spacious layout emphasizing leadership and achievements.', TRUE, TRUE, jsonb_build_object('key','executive','version',1,'layout','single','defaultTheme','executive-navy','sectionOrder',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','PROJECT','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','PROJECT','LANGUAGES'),'theme',jsonb_build_object('primary','#10253f','accent','#9a7530','text','#182433','muted','#5d6875','border','#c7b68f','headingFont','TIMES','bodyFont','TIMES'))),
('academic', 'Dense long-form layout suited to research and academic CVs.', TRUE, TRUE, jsonb_build_object('key','academic','version',1,'layout','single','defaultTheme','academic','sectionOrder',jsonb_build_array('SUMMARY','EDUCATION','EXPERIENCE','PROJECT','CERTIFICATION','SKILL','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','EDUCATION','EXPERIENCE','PROJECT','CERTIFICATION','SKILL','LANGUAGES'),'theme',jsonb_build_object('primary','#1f2937','accent','#374151','text','#111827','muted','#4b5563','border','#9ca3af','headingFont','TIMES','bodyFont','TIMES'))),
('student', 'Education-first layout for graduates and early-career applicants.', TRUE, TRUE, jsonb_build_object('key','student','version',1,'layout','single','defaultTheme','student-green','sectionOrder',jsonb_build_array('SUMMARY','EDUCATION','PROJECT','SKILL','EXPERIENCE','CERTIFICATION','LANGUAGES'),'requiredSections',jsonb_build_array('EDUCATION'),'supportedSections',jsonb_build_array('SUMMARY','EDUCATION','PROJECT','SKILL','EXPERIENCE','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#12372a','accent','#16856b','text','#17352d','muted','#55736a','border','#9dd5c4','headingFont','HELVETICA','bodyFont','HELVETICA'))),
('developer', 'Technical two-column layout with prominent skills and links.', TRUE, TRUE, jsonb_build_object('key','developer','version',1,'layout','sidebar','defaultTheme','developer','sectionOrder',jsonb_build_array('SUMMARY','SKILL','EXPERIENCE','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'sidebarSections',jsonb_build_array('SKILL','CERTIFICATION','EDUCATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','SKILL','EXPERIENCE','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#10212b','accent','#00a67d','text','#132832','muted','#55717d','border','#9edbcc','headingFont','COURIER','bodyFont','HELVETICA'))),
('designer', 'Portfolio-forward two-column layout with strong visual hierarchy.', TRUE, TRUE, jsonb_build_object('key','designer','version',1,'layout','sidebar','defaultTheme','designer-violet','sectionOrder',jsonb_build_array('SUMMARY','PROJECT','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'sidebarSections',jsonb_build_array('SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','PROJECT','EXPERIENCE','SKILL','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#29194f','accent','#7c3aed','text','#24163f','muted','#71658a','border','#c4b5fd','headingFont','HELVETICA','bodyFont','HELVETICA'))),
('corporate', 'Structured grid and muted palette for enterprise applications.', TRUE, TRUE, jsonb_build_object('key','corporate','version',1,'layout','single','defaultTheme','corporate-slate','sectionOrder',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'supportedSections',jsonb_build_array('SUMMARY','EXPERIENCE','SKILL','PROJECT','EDUCATION','CERTIFICATION','LANGUAGES'),'theme',jsonb_build_object('primary','#243447','accent','#526d82','text','#243447','muted','#657786','border','#b8c4ce','headingFont','HELVETICA','bodyFont','HELVETICA')))
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    configuration = EXCLUDED.configuration;
