CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN', 'RECRUITER')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    display_name VARCHAR(100) NULL,
    phone VARCHAR(50) NULL,
    location VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id),
    CONSTRAINT uk_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(500) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(2000) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_resumes PRIMARY KEY (id),
    CONSTRAINT chk_resumes_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS resume_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resume_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_resume_sections PRIMARY KEY (id),
    CONSTRAINT fk_resume_sections_resume FOREIGN KEY (resume_id) REFERENCES resumes (id)
);

CREATE TABLE IF NOT EXISTS educations (
    id BIGINT NOT NULL,
    institution VARCHAR(255) NOT NULL,
    degree VARCHAR(255) NOT NULL,
    start_year INTEGER NULL,
    end_year INTEGER NULL,
    CONSTRAINT pk_educations PRIMARY KEY (id),
    CONSTRAINT fk_educations_section FOREIGN KEY (id) REFERENCES resume_sections (id)
);

CREATE TABLE IF NOT EXISTS experiences (
    id BIGINT NOT NULL,
    employer VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    start_date VARCHAR(50) NULL,
    end_date VARCHAR(50) NULL,
    CONSTRAINT pk_experiences PRIMARY KEY (id),
    CONSTRAINT fk_experiences_section FOREIGN KEY (id) REFERENCES resume_sections (id)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(4000) NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_section FOREIGN KEY (id) REFERENCES resume_sections (id)
);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    proficiency_level VARCHAR(100) NULL,
    CONSTRAINT pk_skills PRIMARY KEY (id),
    CONSTRAINT fk_skills_section FOREIGN KEY (id) REFERENCES resume_sections (id)
);

CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    issued_by VARCHAR(255) NULL,
    CONSTRAINT pk_certifications PRIMARY KEY (id),
    CONSTRAINT fk_certifications_section FOREIGN KEY (id) REFERENCES resume_sections (id)
);

CREATE INDEX idx_resumes_user_status_created
    ON resumes (user_id, status, created_at);

CREATE INDEX idx_resume_sections_resume_order
    ON resume_sections (resume_id, display_order);

CREATE INDEX idx_refresh_tokens_user_expiry
    ON refresh_tokens (user_id, expires_at);
