CREATE TABLE ai_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider_key VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    capabilities JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_providers PRIMARY KEY (id),
    CONSTRAINT uk_ai_providers_key UNIQUE (provider_key)
);

CREATE TABLE ai_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    resume_id BIGINT NULL,
    provider_id BIGINT NOT NULL,
    request_type VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    prompt_reference VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_ai_requests PRIMARY KEY (id),
    CONSTRAINT chk_ai_requests_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'RETRYING')),
    CONSTRAINT fk_ai_requests_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ai_requests_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_ai_requests_provider
        FOREIGN KEY (provider_id) REFERENCES ai_providers (id)
);

CREATE INDEX idx_ai_requests_user_created
    ON ai_requests (user_id, created_at);

CREATE INDEX idx_ai_requests_resume_created
    ON ai_requests (resume_id, created_at);

CREATE INDEX idx_ai_requests_status_created
    ON ai_requests (status, created_at);

CREATE TABLE ai_generated_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ai_request_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB NULL,
    applied_to_resume BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_generated_contents PRIMARY KEY (id),
    CONSTRAINT uk_ai_generated_contents_request UNIQUE (ai_request_id),
    CONSTRAINT fk_ai_generated_contents_request
        FOREIGN KEY (ai_request_id) REFERENCES ai_requests (id)
);

CREATE TABLE ai_request_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ai_request_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    latency_ms BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_request_attempts PRIMARY KEY (id),
    CONSTRAINT uk_ai_request_attempts_number UNIQUE (ai_request_id, attempt_number),
    CONSTRAINT fk_ai_request_attempts_request
        FOREIGN KEY (ai_request_id) REFERENCES ai_requests (id)
);

CREATE TABLE ai_usage_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    ai_request_id BIGINT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    cost_estimate NUMERIC(12, 6) NOT NULL DEFAULT 0,
    billing_period_reference VARCHAR(30) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_usage_ledger PRIMARY KEY (id),
    CONSTRAINT fk_ai_usage_ledger_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ai_usage_ledger_provider
        FOREIGN KEY (provider_id) REFERENCES ai_providers (id),
    CONSTRAINT fk_ai_usage_ledger_request
        FOREIGN KEY (ai_request_id) REFERENCES ai_requests (id)
);

CREATE INDEX idx_ai_usage_ledger_user_created
    ON ai_usage_ledger (user_id, created_at);

INSERT INTO ai_providers (
    provider_key,
    display_name,
    is_active
)
VALUES
    ('gemini', 'Google Gemini', TRUE),
    ('openai', 'OpenAI', TRUE)
ON CONFLICT (provider_key) DO UPDATE
SET
    display_name = EXCLUDED.display_name,
    is_active = EXCLUDED.is_active;
