CREATE TABLE job_descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NULL,
    title VARCHAR(255) NULL,
    company_name VARCHAR(255) NULL,
    source_url VARCHAR(1000) NULL,
    content TEXT NOT NULL,
    extracted_skills JSONB NULL,
    seniority_level VARCHAR(100) NULL,
    is_external BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_job_descriptions PRIMARY KEY (id),
    CONSTRAINT fk_job_descriptions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_job_descriptions_user_created
    ON job_descriptions (user_id, created_at);

CREATE TABLE ats_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resume_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    overall_score NUMERIC(5, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ats_reports PRIMARY KEY (id),
    CONSTRAINT chk_ats_reports_score
        CHECK (overall_score >= 0 AND overall_score <= 100),
    CONSTRAINT fk_ats_reports_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_ats_reports_job
        FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id)
);

CREATE INDEX idx_ats_reports_resume_created
    ON ats_reports (resume_id, created_at);

CREATE INDEX idx_ats_reports_job_created
    ON ats_reports (job_description_id, created_at);

CREATE TABLE ats_keyword_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ats_report_id BIGINT NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    found_in_resume BOOLEAN NOT NULL,
    importance_weight NUMERIC(6, 3) NULL,
    CONSTRAINT pk_ats_keyword_matches PRIMARY KEY (id),
    CONSTRAINT fk_ats_keyword_matches_report
        FOREIGN KEY (ats_report_id) REFERENCES ats_reports (id)
);

CREATE INDEX idx_ats_keyword_matches_report
    ON ats_keyword_matches (ats_report_id);

CREATE TABLE ats_missing_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ats_report_id BIGINT NOT NULL,
    skill_name VARCHAR(255) NOT NULL,
    suggested_action TEXT NULL,
    CONSTRAINT pk_ats_missing_skills PRIMARY KEY (id),
    CONSTRAINT fk_ats_missing_skills_report
        FOREIGN KEY (ats_report_id) REFERENCES ats_reports (id)
);

CREATE INDEX idx_ats_missing_skills_report
    ON ats_missing_skills (ats_report_id);

CREATE TABLE ats_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ats_report_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    recommendation_text TEXT NOT NULL,
    CONSTRAINT pk_ats_recommendations PRIMARY KEY (id),
    CONSTRAINT chk_ats_recommendations_category
        CHECK (category IN ('FORMATTING', 'KEYWORDS', 'STRUCTURE', 'CONTENT')),
    CONSTRAINT fk_ats_recommendations_report
        FOREIGN KEY (ats_report_id) REFERENCES ats_reports (id)
);

CREATE INDEX idx_ats_recommendations_report
    ON ats_recommendations (ats_report_id);

CREATE TABLE job_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resume_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    match_score NUMERIC(5, 2) NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_job_matches PRIMARY KEY (id),
    CONSTRAINT chk_job_matches_score
        CHECK (match_score >= 0 AND match_score <= 100),
    CONSTRAINT uk_job_matches_resume_job UNIQUE (resume_id, job_description_id),
    CONSTRAINT fk_job_matches_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_job_matches_job
        FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id)
);

CREATE INDEX idx_job_matches_resume_score
    ON job_matches (resume_id, match_score);
