CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    plan VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    current_user_id BIGINT GENERATED ALWAYS AS (
        CASE
            WHEN is_current THEN user_id
            ELSE NULL
        END
    ) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    CONSTRAINT uk_subscriptions_current_user UNIQUE (current_user_id),
    CONSTRAINT chk_subscriptions_plan
        CHECK (plan IN ('FREE', 'PREMIUM', 'PRO')),
    CONSTRAINT chk_subscriptions_status
        CHECK (status IN ('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE')),
    CONSTRAINT fk_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_subscriptions_user_starts
    ON subscriptions (user_id, starts_at);


CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subscription_id BIGINT NOT NULL,
    provider VARCHAR(80) NOT NULL,
    provider_reference VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payment_transactions PRIMARY KEY (id),
    CONSTRAINT uk_payment_transactions_reference
        UNIQUE (provider, provider_reference),
    CONSTRAINT chk_payment_transactions_status
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED')),
    CONSTRAINT fk_payment_transactions_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
);

CREATE INDEX idx_payment_transactions_subscription_occurred
    ON payment_transactions (subscription_id, occurred_at);


CREATE TABLE usage_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    metric_date DATE NOT NULL,
    metric_name VARCHAR(100) NOT NULL,
    dimension_key VARCHAR(150) NOT NULL DEFAULT '',
    metric_value BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usage_metrics PRIMARY KEY (id),
    CONSTRAINT uk_usage_metrics_rollup
        UNIQUE (metric_date, metric_name, dimension_key)
);

CREATE INDEX idx_usage_metrics_name_date
    ON usage_metrics (metric_name, metric_date);
