CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    before_state JSONB NULL,
    after_state JSONB NULL,
    ip_address VARCHAR(45) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_audit_logs_entity_created
    ON audit_logs (entity_type, entity_id, created_at);

CREATE INDEX idx_audit_logs_user_created
    ON audit_logs (user_id, created_at);


CREATE TABLE admin_action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    admin_user_id BIGINT NOT NULL,
    target_user_id BIGINT NULL,
    action VARCHAR(100) NOT NULL,
    details JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_admin_action_logs_admin
        FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_action_logs_target
        FOREIGN KEY (target_user_id) REFERENCES users(id)
);

CREATE INDEX idx_admin_action_logs_admin_created
    ON admin_action_logs (admin_user_id, created_at);
