CREATE TABLE templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    preview_url VARCHAR(500) NULL,
    is_system BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    configuration JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_templates PRIMARY KEY (id),
    CONSTRAINT uk_templates_name UNIQUE (name)
);

ALTER TABLE resumes
    ADD COLUMN target_job_title VARCHAR(255) NULL,
    ADD COLUMN template_id BIGINT NULL,
    ADD CONSTRAINT fk_resumes_template
        FOREIGN KEY (template_id) REFERENCES templates (id);

CREATE INDEX idx_resumes_template
    ON resumes (template_id);

CREATE TABLE resume_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resume_id BIGINT NOT NULL,
    template_id BIGINT NULL,
    version_number INTEGER NOT NULL,
    source_type VARCHAR(50) NOT NULL DEFAULT 'USER_EDIT',
    label VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resume_versions PRIMARY KEY (id),
    CONSTRAINT uk_resume_versions_number UNIQUE (resume_id, version_number),
    CONSTRAINT chk_resume_versions_source
        CHECK (source_type IN ('USER_EDIT', 'AI_GENERATED', 'AI_IMPROVED', 'ROLLBACK')),
    CONSTRAINT fk_resume_versions_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_resume_versions_template
        FOREIGN KEY (template_id) REFERENCES templates (id)
);

CREATE INDEX idx_resume_versions_resume_created
    ON resume_versions (resume_id, created_at);

CREATE INDEX idx_resume_versions_template
    ON resume_versions (template_id);

CREATE TABLE resume_version_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resume_version_id BIGINT NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resume_version_snapshots PRIMARY KEY (id),
    CONSTRAINT uk_resume_version_snapshots_version UNIQUE (resume_version_id),
    CONSTRAINT fk_resume_version_snapshots_version
        FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id)
);

INSERT INTO templates (
    name,
    description,
    is_system,
    is_active
)
VALUES (
    'classic',
    'Clean, ATS-friendly single-column template.',
    TRUE,
    TRUE
)
ON CONFLICT (name) DO NOTHING;
