CREATE TABLE ai_prompt_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workflow VARCHAR(80) NOT NULL,
    version INTEGER NOT NULL,
    locale VARCHAR(20) NOT NULL DEFAULT 'en-US',
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    system_instruction TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_ai_prompt_templates_workflow_version_locale
        UNIQUE (workflow, version, locale)
);

CREATE INDEX idx_ai_prompt_templates_lookup
    ON ai_prompt_templates (workflow, locale, status);


INSERT INTO ai_prompt_templates (
    workflow,
    version,
    locale,
    status,
    system_instruction
)
VALUES (
    'resume-summary',
    1,
    'en-US',
    'PUBLISHED',
    'You are a professional resume-writing assistant. Create a concise, factual professional summary from only the supplied information. Never invent employment, education, dates, metrics, or skills. Return only polished plain text.'
)
ON CONFLICT ON CONSTRAINT uk_ai_prompt_templates_workflow_version_locale
DO UPDATE SET
    system_instruction = EXCLUDED.system_instruction;
