ALTER TABLE ai_prompt_templates
    ADD COLUMN category VARCHAR(80) NOT NULL DEFAULT 'RESUME',
    ADD COLUMN author_id BIGINT NULL,
    ADD COLUMN reviewed_at TIMESTAMPTZ NULL,
    ADD COLUMN published_at TIMESTAMPTZ NULL;