CREATE TABLE user_ai_settings (
    user_id BIGINT NOT NULL,
    mode VARCHAR(20) NOT NULL DEFAULT 'PLATFORM',
    preferred_provider VARCHAR(50) NOT NULL DEFAULT 'gemini',
    allow_platform_fallback BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    CONSTRAINT chk_user_ai_settings_mode
        CHECK (mode IN ('PLATFORM', 'BYOK')),
    CONSTRAINT chk_user_ai_settings_provider
        CHECK (preferred_provider IN ('gemini', 'openai')),
    CONSTRAINT fk_user_ai_settings_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);


ALTER TABLE ai_requests
    ADD COLUMN credential_source VARCHAR(20) NOT NULL DEFAULT 'PLATFORM',
    ADD CONSTRAINT chk_ai_requests_credential_source
        CHECK (credential_source IN ('PLATFORM', 'BYOK'));


CREATE TABLE user_ai_provider_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    encrypted_key BYTEA NOT NULL,
    initialization_vector BYTEA NOT NULL,
    key_version INTEGER NOT NULL DEFAULT 1,
    key_hint VARCHAR(12) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_ai_credentials_provider
        UNIQUE (user_id, provider),
    CONSTRAINT chk_user_ai_credentials_provider
        CHECK (provider IN ('gemini', 'openai')),
    CONSTRAINT fk_user_ai_credentials_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
