CREATE TABLE pdf_exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    resume_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    byte_size BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_pdf_exports_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_pdf_exports_resume
        FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

CREATE INDEX idx_pdf_exports_user_created
    ON pdf_exports (user_id, created_at);

CREATE INDEX idx_pdf_exports_resume_created
    ON pdf_exports (resume_id, created_at);
