package com.airesumebuilder.feature.resume.service;

import com.airesumebuilder.common.exception.*;
import com.airesumebuilder.feature.resume.dto.request.ResumeSectionRequest;
import com.airesumebuilder.feature.resume.dto.response.ResumeSectionResponse;
import com.airesumebuilder.feature.resume.entity.*;
import com.airesumebuilder.feature.resume.repository.*;
import com.airesumebuilder.feature.resume.version.service.ResumeVersionService;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ResumeSectionService {
    private final ResumeRepository resumes; private final ResumeSectionRepository sections; private final ResumeVersionService versions;
    public ResumeSectionService(ResumeRepository resumes,ResumeSectionRepository sections,ResumeVersionService versions){this.resumes=resumes;this.sections=sections;this.versions=versions;}

    @Transactional(readOnly=true) public List<ResumeSectionResponse> list(String email,long resumeId){Resume resume=resume(email,resumeId);return resume.getSections().stream().sorted(Comparator.comparing(ResumeSection::getDisplayOrder).thenComparing(ResumeSection::getId)).map(this::response).toList();}
    @Transactional public ResumeSectionResponse create(String email,long resumeId,ResumeSectionRequest request){Resume resume=resume(email,resumeId);ResumeSection section=build(request);section.setResume(resume);section.setDisplayOrder(request.displayOrder()==null?resume.getSections().size():request.displayOrder());ResumeSection saved=sections.save(section);resume.getSections().add(saved);versions.snapshot(resume,"USER_EDIT","Added "+request.type().toLowerCase(Locale.ROOT)+" section");return response(saved);}
    @Transactional public ResumeSectionResponse update(String email,long resumeId,long sectionId,ResumeSectionRequest request){Resume resume=resume(email,resumeId);ResumeSection existing=owned(resume,sectionId);if(!type(existing).equals(request.type()))throw new ValidationException("A section's type cannot be changed.");apply(existing,request);if(request.displayOrder()!=null)existing.setDisplayOrder(request.displayOrder());ResumeSection saved=sections.save(existing);versions.snapshot(resume,"USER_EDIT","Updated "+request.type().toLowerCase(Locale.ROOT)+" section");return response(saved);}
    @Transactional public void delete(String email,long resumeId,long sectionId){Resume resume=resume(email,resumeId);ResumeSection existing=owned(resume,sectionId);resume.getSections().remove(existing);sections.delete(existing);normalize(resume);versions.snapshot(resume,"USER_EDIT","Deleted resume section");}
    @Transactional public List<ResumeSectionResponse> reorder(String email,long resumeId,List<Long> ids){Resume resume=resume(email,resumeId);Set<Long> actual=new HashSet<>();resume.getSections().forEach(s->actual.add(s.getId()));if(ids.size()!=actual.size()||!actual.equals(new HashSet<>(ids)))throw new ValidationException("Section order must contain every section exactly once.");if(new HashSet<>(ids).size()!=ids.size())throw new ValidationException("Section order contains duplicate identifiers.");Map<Long,ResumeSection> byId=new HashMap<>();resume.getSections().forEach(s->byId.put(s.getId(),s));for(int i=0;i<ids.size();i++)byId.get(ids.get(i)).setDisplayOrder(i);sections.saveAll(resume.getSections());versions.snapshot(resume,"USER_EDIT","Reordered resume sections");return ids.stream().map(byId::get).map(this::response).toList();}

    private Resume resume(String email,long id){return resumes.findByIdAndUserEmailAndDeletedAtIsNull(id,email).orElseThrow(()->new ResourceNotFoundException("Resume not found."));}
    private ResumeSection owned(Resume resume,long id){return resume.getSections().stream().filter(s->Objects.equals(s.getId(),id)).findFirst().orElseThrow(()->new ResourceNotFoundException("Resume section not found."));}
    private ResumeSection build(ResumeSectionRequest r){ResumeSection value=switch(r.type()){case"EDUCATION"->new Education();case"EXPERIENCE"->new Experience();case"PROJECT"->new Project();case"SKILL"->new Skill();case"CERTIFICATION"->new Certification();default->throw new ValidationException("Unsupported resume section type.");};apply(value,r);return value;}
    private void apply(ResumeSection s,ResumeSectionRequest r){switch(s){case Education x->{x.setInstitution(required(r.institution(),"Institution"));x.setDegree(required(r.degree(),"Degree"));x.setStartYear(r.startYear());x.setEndYear(r.endYear());if(r.startYear()!=null&&r.endYear()!=null&&r.endYear()<r.startYear())throw new ValidationException("Education end year cannot precede start year.");}case Experience x->{x.setEmployer(required(r.employer(),"Employer"));x.setRole(required(r.role(),"Role"));x.setStartDate(blank(r.startDate()));x.setEndDate(blank(r.endDate()));}case Project x->{x.setName(required(r.name(),"Project name"));x.setDescription(blank(r.description()));}case Skill x->{x.setName(required(r.name(),"Skill name"));x.setProficiencyLevel(blank(r.proficiencyLevel()));}case Certification x->{x.setName(required(r.name(),"Certification name"));x.setIssuedBy(blank(r.issuedBy()));}default->throw new ValidationException("Unsupported resume section type.");}}
    private String required(String v,String label){if(v==null||v.isBlank())throw new ValidationException(label+" is required.");return v.trim();}private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
    private void normalize(Resume r){List<ResumeSection> ordered=r.getSections().stream().sorted(Comparator.comparing(ResumeSection::getDisplayOrder)).toList();for(int i=0;i<ordered.size();i++)ordered.get(i).setDisplayOrder(i);}
    private String type(ResumeSection s){return s instanceof Education?"EDUCATION":s instanceof Experience?"EXPERIENCE":s instanceof Project?"PROJECT":s instanceof Skill?"SKILL":"CERTIFICATION";}
    private ResumeSectionResponse response(ResumeSection s){String t=type(s);return switch(s){case Education x->new ResumeSectionResponse(x.getId(),t,x.getDisplayOrder(),x.getInstitution(),x.getDegree(),x.getStartYear(),x.getEndYear(),null,null,null,null,null,null,null,null);case Experience x->new ResumeSectionResponse(x.getId(),t,x.getDisplayOrder(),null,null,null,null,x.getEmployer(),x.getRole(),x.getStartDate(),x.getEndDate(),null,null,null,null);case Project x->new ResumeSectionResponse(x.getId(),t,x.getDisplayOrder(),null,null,null,null,null,null,null,null,x.getName(),x.getDescription(),null,null);case Skill x->new ResumeSectionResponse(x.getId(),t,x.getDisplayOrder(),null,null,null,null,null,null,null,null,x.getName(),null,x.getProficiencyLevel(),null);case Certification x->new ResumeSectionResponse(x.getId(),t,x.getDisplayOrder(),null,null,null,null,null,null,null,null,x.getName(),null,null,x.getIssuedBy());default->throw new IllegalStateException("Unsupported resume section type.");};}
}
